### ISSUE TITLE
Docker network 'playfab' not automatically created

### ISSUE THREAD

**Issue by RiederAlex** [PlayFab/LocalMultiplayerAgent#10]
Running the MockAgent.exe with -lcow and a Linux container configuration requires the docker network 'playfab' existing, otherwise the following exception will be thrown:

`Unhandled exception. Docker.DotNet.DockerContainerNotFoundException: Docker API responded with status code=NotFound, response={"message":"network playfab not found"}`

It would be nice if either this is explicitly documented somewhere or if the network gets created automatically

**Comment by dgkanatsios** [comment]
Thanks for that. There is a `SetupLinuxContainersOnWindows.ps1` file that you can use, which was omitted from the documentation. Will change that ASAP.
