### ISSUE TITLE
Inconsistent gsdkConfig.json between production and LocalMultiplayerAgent

### ISSUE THREAD

**Issue by najadojo** [PlayFab/LocalMultiplayerAgent#11]
I'm using LocalMultiplayerAgent for Windows to test my game server before pushing builds into PlayFab production environment and I've found that the gsdkConfig.json isn't produced as I expect.

My MultiplayerSettings.json contains the following at the top level:
```
    "PortMappingsList": [
        [
            {
                "NodePort": 56100,
                "GamePort": {
                    "Name": "game_port",
                    "Number": 7777,
                    "Protocol": "UDP"
                }
            }
        ]
    ],
```

When `"RunContainer": false,` LMA writes out a configuration similar to:

```
{
  "heartbeatEndpoint": "127.0.0.1:56001",
  "sessionHostId": "xxx",
  "vmId": "xxx",
  "logFolder": "C:\\GameLogs",
  "certificateFolder": "C:\\GameCertificates",
  "sharedContentFolder": "C:\\GameSharedContent",
  "gamePorts": {
    "game_port": "56100"
  },
  "publicIpV4Address": "127.0.0.1",
  "gameServerConnectionInfo": {
    "publicIpV4Adress": "127.0.0.1",
    "gamePortsConfiguration": [
      {
        "name": "game_port",
        "serverListeningPort": 56100
      }
    ]
  },
  "fullyQualifiedDomainName": "localhost"
}
```

Here its using the public ports in the `serverListeningPort` field and `clientConnectionPort` is missing from the configuration completely. This causes GSDK from C++ to report 0 for the client port.

But when `"RunContainer": true,` LMA writes out a configuration similar to:

```
{
  "heartbeatEndpoint": "1.1.1.1:56001",
  "sessionHostId": "xxx",
  "vmId": "xxx",
  "logFolder": "C:\\GameLogs\\",
  "certificateFolder": "C:\\GameCertificates",
  "sharedContentFolder": "C:\\GameSharedContent",
  "gamePorts": {
    "game_port": "7777"
  },
  "publicIpV4Address": "127.0.0.1",
  "gameServerConnectionInfo": {
    "publicIpV4Adress": "127.0.0.1",
    "gamePortsConfiguration": [
      {
        "name": "game_port",
        "serverListeningPort": 7777
      }
    ]
  },
  "fullyQualifiedDomainName": "localhost"
}
```

The `serverListeningPort` is as I expect here but `clientConnectionPort` and still missing.

I'm getting configuration that I expect in production that looks something like:

```
{
  "heartbeatEndpoint": "1.1.1.1:56001",
  "sessionHostId": "xxx",
  "vmId": "xxx",
  "logFolder": "C:\\GameLogs\\",
  "certificateFolder": "C:\\GameCertificates",
  "sharedContentFolder": "C:\\GameSharedContent",
  "buildMetadata": {},
  "gamePorts": {
    "game_port": "7777"
  },
  "publicIpV4Address": "2.2.2.2",
  "gameServerConnectionInfo": {
    "publicIpV4Adress": "2.2.2.2",
    "gamePortsConfiguration": [
      {
        "name": "game_port",
        "serverListeningPort": 7777,
        "clientConnectionPort": 30000
      }
    ]
  },
  "fullyQualifiedDomainName": "xxx-azurebatch-cloudservice.westus.cloudapp.azure.com"
}
```

**Comment by dgkanatsios** [comment]
Thanks for reporting that!
It appears that the issue can be mitigated by assigning the port number to `PublicPort` as well, confirmed that this worked for both `RunContainer:true` and `RunContainer:false`. Will check the codebase and update the issue with the optimal solution.

```json
"PortMappingsList": [
        [
            {
		"NodePort": 56100,
                "PublicPort": 56100,
                "GamePort": {
                    "Name": "game_port",
                    "Number": 7777,
                    "Protocol": "TCP"
                }
            }
        ]
    ],
```

**Comment by dgkanatsios** [comment]
hey @najadojo, we just pushed 0.9.3 with a fix that will automatically create a `PublicPort` if it's missing from `MultiplayerSettings.json`, it will have the same value as `NodePort`. In this way, you can omit `PublicPort` from `MultiplayerSettings.json` file. Can you try it and let us know if it works?

**Comment by najadojo** [comment]
Works as expected. Thanks for the quick fix.
