### ISSUE TITLE
Provided 'MultiplayerSettingsLinuxContainersOnWindowsSample.json' is wrong

### ISSUE THREAD

**Issue by RiederAlex** [PlayFab/LocalMultiplayerAgent#8]
The provided 'MultiplayerSettingsLinuxContainersOnWindowsSample.json' uses wrong tags and does not work 'as-is' anymore.

Examples:
- "ServerStartParameters" is now called "ContainerStartParameters"
- "PortMappingList" is toplevel instead of "ServerStartParameters.PortMappingList"

**Comment by dgkanatsios** [comment]
Fixed the sample [here](https://github.com/PlayFab/LocalMultiplayerAgent/blob/master/linuxContainersOnWindows.md), updated fix on the Releases section coming soon. Thanks!

**Comment by dgkanatsios** [comment]
Updated version of LocalMultiplayerAgent, closing for now, let us know if you have any more issues.
